kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"dynatrace":"operator","operator":"dynakube"},"name":"dynatrace-operator","namespace":"dynatrace"},"spec":{"replicas":1,"revisionHistoryLimit":1,"selector":{"matchLabels":{"name":"dynatrace-operator"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"dynatrace":"operator","name":"dynatrace-operator","operator":"dynakube"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64","arm64"]},{"key":"beta.kubernetes.io/os","operator":"In","values":["linux"]}]},{"matchExpressions":[{"key":"kubernetes.io/arch","operator":"In","values":["amd64","arm64"]},{"key":"kubernetes.io/os","operator":"In","values":["linux"]}]}]}}},"containers":[{"args":["operator"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"RELATED_IMAGE_DYNATRACE_ONEAGENT","value":"registry.connect.redhat.com/dynatrace/oneagent"}],"image":"registry.connect.redhat.com/dynatrace/dynatrace-operator:v0.2.1","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/healthz","port":"server-port","scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":10},"name":"dynatrace-operator","ports":[{"containerPort":8080,"name":"metrics"},{"containerPort":10080,"name":"server-port"}],"readinessProbe":{"httpGet":{"path":"/healthz","port":"server-port","scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":10},"resources":{"limits":{"cpu":"100m","memory":"256Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}],"serviceAccountName":"dynatrace-operator"}}}}
  name: dynatrace-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: dynakube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dynatrace-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        dynatrace: operator
        name: dynatrace-operator
        operator: dynakube
    spec:
      restartPolicy: Always
      serviceAccountName: dynatrace-operator
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: server-port
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: dynatrace-operator
          livenessProbe:
            httpGet:
              path: /healthz
              port: server-port
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: RELATED_IMAGE_DYNATRACE_ONEAGENT
              value: registry.connect.redhat.com/dynatrace/oneagent
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: server-port
              containerPort: 10080
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'registry.connect.redhat.com/dynatrace/dynatrace-operator:v0.2.1'
          args:
            - operator
      serviceAccount: dynatrace-operator
      dnsPolicy: ClusterFirst
  
